// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddHost(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddHost'](arg1, arg2, arg3);
}

export function DeleteHost(arg1, arg2) {
  return window['go']['main']['App']['DeleteHost'](arg1, arg2);
}

export function GetAllGroupNames() {
  return window['go']['main']['App']['GetAllGroupNames']();
}

export function GetHostsText() {
  return window['go']['main']['App']['GetHostsText']();
}

export function GetInUseHostsText() {
  return window['go']['main']['App']['GetInUseHostsText']();
}

export function GetList() {
  return window['go']['main']['App']['GetList']();
}

export function GetListByGroup() {
  return window['go']['main']['App']['GetListByGroup']();
}

export function SaveAllGroupHosts(arg1, arg2) {
  return window['go']['main']['App']['SaveAllGroupHosts'](arg1, arg2);
}

export function SaveAllHosts(arg1) {
  return window['go']['main']['App']['SaveAllHosts'](arg1);
}

export function SaveAllInUseHosts(arg1) {
  return window['go']['main']['App']['SaveAllInUseHosts'](arg1);
}

export function SetGroupName(arg1, arg2) {
  return window['go']['main']['App']['SetGroupName'](arg1, arg2);
}

export function SwitchByGroupName(arg1, arg2) {
  return window['go']['main']['App']['SwitchByGroupName'](arg1, arg2);
}

export function SwitchByHostnameId(arg1, arg2, arg3) {
  return window['go']['main']['App']['SwitchByHostnameId'](arg1, arg2, arg3);
}
