// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddHost(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddHost'](arg1, arg2, arg3);
}

export function DeleteHost(arg1, arg2) {
  return window['go']['main']['App']['DeleteHost'](arg1, arg2);
}

export function GetHosts() {
  return window['go']['main']['App']['GetHosts']();
}

export function GetHostsList() {
  return window['go']['main']['App']['GetHostsList']();
}

export function SaveAllHosts(arg1) {
  return window['go']['main']['App']['SaveAllHosts'](arg1);
}

export function SwitchByGroupName(arg1, arg2) {
  return window['go']['main']['App']['SwitchByGroupName'](arg1, arg2);
}

export function SwitchByHostname(arg1, arg2, arg3) {
  return window['go']['main']['App']['SwitchByHostname'](arg1, arg2, arg3);
}
